
public class exceptionTest {

	public static void main(String[] args) {
		
		int a = 1 / 0;
		
		System.out.println("outside of try statement");
	}

}
